apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stevea-worker-as-a-service
  name: deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: stevea-worker-as-a-service
subjects:
- kind: ServiceAccount
  name: cicd
  namespace: stevea-worker-as-a-service
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cicd-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-role-binding
subjects:
- kind: ServiceAccount
  name: cicd
  namespace: stevea-worker-as-a-service
roleRef:
  kind: ClusterRole
  name: cicd-role
  apiGroup: rbac.authorization.k8s.io
